# Generated by Django 5.0.6 on 2024-06-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_productattr_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="category"),
        ),
    ]
