# Generated by Django 5.0.6 on 2024-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_usertoken_expire_at_usertoken_token_usertoken_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertoken",
            name="browser",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usertoken",
            name="device",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usertoken",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usertoken",
            name="language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usertoken",
            name="platform",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usertoken",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usertoken",
            name="version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
