# Generated by Django 5.0.6 on 2024-05-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_usertoken_browser_usertoken_device_usertoken_ip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertoken",
            name="sec_ua",
            field=models.TextField(blank=True, null=True),
        ),
    ]
