version: '3.7'
name: django_admin
services:
  mysql8:
    image: mysql:8
    container_name: da_mysql8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: django_admin
      MYSQL_DATABASE: django_admin
      MYSQL_USER: django_admin
      MYSQL_PASSWORD: django_admin
    volumes:
      - ./mysql:/var/lib/mysql
    command:  --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      
  mongo:
    image: mongo:4.2
    container_name: da_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

  redis:
    image: redis:5
    container_name: da_redis
    ports:
      - "6379:6379"