version: '3.7'
name: django_admin
services:
  postgres:
    image: postgres:12
    container_name: da_postgres
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: myapp
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

      
  mongo:
    image: mongo:4.2
    container_name: da_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

  redis:
    image: redis:5
    container_name: da_redis
    ports:
      - "6379:6379"