# Generated by Django 5.0.6 on 2024-06-04 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
        migrations.AddField(
            model_name="article",
            name="tag_ids",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="articlecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.articlecategory",
            ),
        ),
    ]
